// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_type::Agent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agents`.
///
/// Obtain a handle from the [`AgentsTableAccess::agents`] method on [`super::RemoteTables`],
/// like `ctx.db.agents()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agents().on_insert(...)`.
pub struct AgentsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Agent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agents`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentsTableHandle`], which mediates access to the table `agents`.
    fn agents(&self) -> AgentsTableHandle<'_>;
}

impl AgentsTableAccess for super::RemoteTables {
    fn agents(&self) -> AgentsTableHandle<'_> {
        AgentsTableHandle {
            imp: self.imp.get_table::<Agent>("agents"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentsInsertCallbackId(__sdk::CallbackId);
pub struct AgentsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentsTableHandle<'ctx> {
    type Row = Agent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Agent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentsInsertCallbackId {
        AgentsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentsDeleteCallbackId {
        AgentsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentsTableHandle<'ctx> {
    type UpdateCallbackId = AgentsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentsUpdateCallbackId {
        AgentsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `name` unique index on the table `agents`,
/// which allows point queries on the field of the same name
/// via the [`AgentsNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agents().name().find(...)`.
pub struct AgentsNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Agent, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentsTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `agents`.
    pub fn name(&self) -> AgentsNameUnique<'ctx> {
        AgentsNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentsNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Agent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Agent>("agents");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Agent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Agent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Agent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agentsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Agent`.
    fn agents(&self) -> __sdk::__query_builder::Table<Agent>;
}

impl agentsQueryTableAccess for __sdk::QueryTableAccessor {
    fn agents(&self) -> __sdk::__query_builder::Table<Agent> {
        __sdk::__query_builder::Table::new("agents")
    }
}
