// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Agent {
    pub name: String,
    pub handler_type: String,
    pub status: String,
    pub current_task_id: u64,
    pub capabilities: String,
    pub last_heartbeat: u64,
    pub last_seen: u64,
}

impl __sdk::InModule for Agent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Agent`.
///
/// Provides typed access to columns for query building.
pub struct AgentCols {
    pub name: __sdk::__query_builder::Col<Agent, String>,
    pub handler_type: __sdk::__query_builder::Col<Agent, String>,
    pub status: __sdk::__query_builder::Col<Agent, String>,
    pub current_task_id: __sdk::__query_builder::Col<Agent, u64>,
    pub capabilities: __sdk::__query_builder::Col<Agent, String>,
    pub last_heartbeat: __sdk::__query_builder::Col<Agent, u64>,
    pub last_seen: __sdk::__query_builder::Col<Agent, u64>,
}

impl __sdk::__query_builder::HasCols for Agent {
    type Cols = AgentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentCols {
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            handler_type: __sdk::__query_builder::Col::new(table_name, "handler_type"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            current_task_id: __sdk::__query_builder::Col::new(table_name, "current_task_id"),
            capabilities: __sdk::__query_builder::Col::new(table_name, "capabilities"),
            last_heartbeat: __sdk::__query_builder::Col::new(table_name, "last_heartbeat"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
        }
    }
}

/// Indexed column accessor struct for the table `Agent`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentIxCols {
    pub name: __sdk::__query_builder::IxCol<Agent, String>,
}

impl __sdk::__query_builder::HasIxCols for Agent {
    type IxCols = AgentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Agent {}
