// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ArchivedTask {
    pub id: u64,
    pub original_task_id: u64,
    pub task_uuid: String,
    pub from_agent: String,
    pub to_agent: String,
    pub claimed_by: String,
    pub title: String,
    pub payload: String,
    pub status: String,
    pub priority: u8,
    pub session_ref: String,
    pub attempt_number: u32,
    pub retry_count: u32,
    pub parent_task_id: Option<u64>,
    pub created_at: u64,
    pub updated_at: u64,
    pub claimed_at: u64,
    pub completed_at: u64,
    pub result: String,
    pub archived_at: u64,
}

impl __sdk::InModule for ArchivedTask {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ArchivedTask`.
///
/// Provides typed access to columns for query building.
pub struct ArchivedTaskCols {
    pub id: __sdk::__query_builder::Col<ArchivedTask, u64>,
    pub original_task_id: __sdk::__query_builder::Col<ArchivedTask, u64>,
    pub task_uuid: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub from_agent: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub to_agent: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub claimed_by: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub title: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub payload: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub status: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub priority: __sdk::__query_builder::Col<ArchivedTask, u8>,
    pub session_ref: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub attempt_number: __sdk::__query_builder::Col<ArchivedTask, u32>,
    pub retry_count: __sdk::__query_builder::Col<ArchivedTask, u32>,
    pub parent_task_id: __sdk::__query_builder::Col<ArchivedTask, Option<u64>>,
    pub created_at: __sdk::__query_builder::Col<ArchivedTask, u64>,
    pub updated_at: __sdk::__query_builder::Col<ArchivedTask, u64>,
    pub claimed_at: __sdk::__query_builder::Col<ArchivedTask, u64>,
    pub completed_at: __sdk::__query_builder::Col<ArchivedTask, u64>,
    pub result: __sdk::__query_builder::Col<ArchivedTask, String>,
    pub archived_at: __sdk::__query_builder::Col<ArchivedTask, u64>,
}

impl __sdk::__query_builder::HasCols for ArchivedTask {
    type Cols = ArchivedTaskCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ArchivedTaskCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            original_task_id: __sdk::__query_builder::Col::new(table_name, "original_task_id"),
            task_uuid: __sdk::__query_builder::Col::new(table_name, "task_uuid"),
            from_agent: __sdk::__query_builder::Col::new(table_name, "from_agent"),
            to_agent: __sdk::__query_builder::Col::new(table_name, "to_agent"),
            claimed_by: __sdk::__query_builder::Col::new(table_name, "claimed_by"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            payload: __sdk::__query_builder::Col::new(table_name, "payload"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            priority: __sdk::__query_builder::Col::new(table_name, "priority"),
            session_ref: __sdk::__query_builder::Col::new(table_name, "session_ref"),
            attempt_number: __sdk::__query_builder::Col::new(table_name, "attempt_number"),
            retry_count: __sdk::__query_builder::Col::new(table_name, "retry_count"),
            parent_task_id: __sdk::__query_builder::Col::new(table_name, "parent_task_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            claimed_at: __sdk::__query_builder::Col::new(table_name, "claimed_at"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
            result: __sdk::__query_builder::Col::new(table_name, "result"),
            archived_at: __sdk::__query_builder::Col::new(table_name, "archived_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ArchivedTask`.
///
/// Provides typed access to indexed columns for query building.
pub struct ArchivedTaskIxCols {
    pub id: __sdk::__query_builder::IxCol<ArchivedTask, u64>,
}

impl __sdk::__query_builder::HasIxCols for ArchivedTask {
    type IxCols = ArchivedTaskIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ArchivedTaskIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ArchivedTask {}
