// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Event {
    pub id: u64,
    pub event_type: String,
    pub agent: String,
    pub task_ref: u64,
    pub detail: String,
    pub timestamp: u64,
}

impl __sdk::InModule for Event {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Event`.
///
/// Provides typed access to columns for query building.
pub struct EventCols {
    pub id: __sdk::__query_builder::Col<Event, u64>,
    pub event_type: __sdk::__query_builder::Col<Event, String>,
    pub agent: __sdk::__query_builder::Col<Event, String>,
    pub task_ref: __sdk::__query_builder::Col<Event, u64>,
    pub detail: __sdk::__query_builder::Col<Event, String>,
    pub timestamp: __sdk::__query_builder::Col<Event, u64>,
}

impl __sdk::__query_builder::HasCols for Event {
    type Cols = EventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            event_type: __sdk::__query_builder::Col::new(table_name, "event_type"),
            agent: __sdk::__query_builder::Col::new(table_name, "agent"),
            task_ref: __sdk::__query_builder::Col::new(table_name, "task_ref"),
            detail: __sdk::__query_builder::Col::new(table_name, "detail"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
        }
    }
}

/// Indexed column accessor struct for the table `Event`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventIxCols {
    pub id: __sdk::__query_builder::IxCol<Event, u64>,
}

impl __sdk::__query_builder::HasIxCols for Event {
    type IxCols = EventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Event {}
