// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Message {
    pub id: u64,
    pub from_agent: String,
    pub to_agent: String,
    pub content: String,
    pub task_ref: u64,
    pub timestamp: u64,
    pub read: bool,
}

impl __sdk::InModule for Message {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Message`.
///
/// Provides typed access to columns for query building.
pub struct MessageCols {
    pub id: __sdk::__query_builder::Col<Message, u64>,
    pub from_agent: __sdk::__query_builder::Col<Message, String>,
    pub to_agent: __sdk::__query_builder::Col<Message, String>,
    pub content: __sdk::__query_builder::Col<Message, String>,
    pub task_ref: __sdk::__query_builder::Col<Message, u64>,
    pub timestamp: __sdk::__query_builder::Col<Message, u64>,
    pub read: __sdk::__query_builder::Col<Message, bool>,
}

impl __sdk::__query_builder::HasCols for Message {
    type Cols = MessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            from_agent: __sdk::__query_builder::Col::new(table_name, "from_agent"),
            to_agent: __sdk::__query_builder::Col::new(table_name, "to_agent"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            task_ref: __sdk::__query_builder::Col::new(table_name, "task_ref"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
            read: __sdk::__query_builder::Col::new(table_name, "read"),
        }
    }
}

/// Indexed column accessor struct for the table `Message`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageIxCols {
    pub id: __sdk::__query_builder::IxCol<Message, u64>,
}

impl __sdk::__query_builder::HasIxCols for Message {
    type IxCols = MessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Message {}
