// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PostTaskArgs {
    pub from_agent: String,
    pub to_agent: String,
    pub title: String,
    pub payload: String,
    pub priority: u8,
    pub session_ref: String,
    pub task_uuid: String,
    pub attempt_number: u32,
    pub parent_task_id: Option<u64>,
}

impl From<PostTaskArgs> for super::Reducer {
    fn from(args: PostTaskArgs) -> Self {
        Self::PostTask {
            from_agent: args.from_agent,
            to_agent: args.to_agent,
            title: args.title,
            payload: args.payload,
            priority: args.priority,
            session_ref: args.session_ref,
            task_uuid: args.task_uuid,
            attempt_number: args.attempt_number,
            parent_task_id: args.parent_task_id,
        }
    }
}

impl __sdk::InModule for PostTaskArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `post_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait post_task {
    /// Request that the remote module invoke the reducer `post_task` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`post_task:post_task_then`] to run a callback after the reducer completes.
    fn post_task(
        &self,
        from_agent: String,
        to_agent: String,
        title: String,
        payload: String,
        priority: u8,
        session_ref: String,
        task_uuid: String,
        attempt_number: u32,
        parent_task_id: Option<u64>,
    ) -> __sdk::Result<()> {
        self.post_task_then(
            from_agent,
            to_agent,
            title,
            payload,
            priority,
            session_ref,
            task_uuid,
            attempt_number,
            parent_task_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `post_task` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn post_task_then(
        &self,
        from_agent: String,
        to_agent: String,
        title: String,
        payload: String,
        priority: u8,
        session_ref: String,
        task_uuid: String,
        attempt_number: u32,
        parent_task_id: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl post_task for super::RemoteReducers {
    fn post_task_then(
        &self,
        from_agent: String,
        to_agent: String,
        title: String,
        payload: String,
        priority: u8,
        session_ref: String,
        task_uuid: String,
        attempt_number: u32,
        parent_task_id: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PostTaskArgs {
                from_agent,
                to_agent,
                title,
                payload,
                priority,
                session_ref,
                task_uuid,
                attempt_number,
                parent_task_id,
            },
            callback,
        )
    }
}
