// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterAgentArgs {
    pub name: String,
    pub handler_type: String,
    pub capabilities: String,
}

impl From<RegisterAgentArgs> for super::Reducer {
    fn from(args: RegisterAgentArgs) -> Self {
        Self::RegisterAgent {
            name: args.name,
            handler_type: args.handler_type,
            capabilities: args.capabilities,
        }
    }
}

impl __sdk::InModule for RegisterAgentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_agent`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_agent {
    /// Request that the remote module invoke the reducer `register_agent` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_agent:register_agent_then`] to run a callback after the reducer completes.
    fn register_agent(
        &self,
        name: String,
        handler_type: String,
        capabilities: String,
    ) -> __sdk::Result<()> {
        self.register_agent_then(name, handler_type, capabilities, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_agent` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_agent_then(
        &self,
        name: String,
        handler_type: String,
        capabilities: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_agent for super::RemoteReducers {
    fn register_agent_then(
        &self,
        name: String,
        handler_type: String,
        capabilities: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterAgentArgs {
                name,
                handler_type,
                capabilities,
            },
            callback,
        )
    }
}
