// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequeueTaskArgs {
    pub task_id: u64,
    pub agent: String,
    pub error: String,
}

impl From<RequeueTaskArgs> for super::Reducer {
    fn from(args: RequeueTaskArgs) -> Self {
        Self::RequeueTask {
            task_id: args.task_id,
            agent: args.agent,
            error: args.error,
        }
    }
}

impl __sdk::InModule for RequeueTaskArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `requeue_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait requeue_task {
    /// Request that the remote module invoke the reducer `requeue_task` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`requeue_task:requeue_task_then`] to run a callback after the reducer completes.
    fn requeue_task(&self, task_id: u64, agent: String, error: String) -> __sdk::Result<()> {
        self.requeue_task_then(task_id, agent, error, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `requeue_task` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn requeue_task_then(
        &self,
        task_id: u64,
        agent: String,
        error: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl requeue_task for super::RemoteReducers {
    fn requeue_task_then(
        &self,
        task_id: u64,
        agent: String,
        error: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequeueTaskArgs {
                task_id,
                agent,
                error,
            },
            callback,
        )
    }
}
