#!/usr/bin/env python3
# =============================================================================
# ManusLocal — Apply OpenFang Configuration
# Merges ManusLocal settings into the existing ~/.openfang/config.toml
# =============================================================================

import os
import shutil
from pathlib import Path

def main():
    openfang_config = Path.home() / ".openfang" / "config.toml"
    manuslocal_config = Path(__file__).parent.parent / "config" / "openfang_manuslocal.toml"
    
    if not openfang_config.exists():
        print(f"Error: OpenFang config not found at {openfang_config}")
        print("Run: openfang init")
        return
    
    # Backup existing config
    backup = str(openfang_config) + ".bak"
    shutil.copy(openfang_config, backup)
    print(f"Backed up existing config to {backup}")
    
    # Read existing config
    with open(openfang_config, "r") as f:
        existing = f.read()
    
    # Read ManusLocal overlay
    with open(manuslocal_config, "r") as f:
        overlay = f.read()
    
    # Write the merged config (overlay takes precedence)
    # Simple approach: write overlay as the new config, preserving existing MCP servers
    with open(openfang_config, "w") as f:
        f.write("# ManusLocal-enhanced OpenFang configuration\n")
        f.write("# Generated by ManusLocal setup — original backed up to config.toml.bak\n\n")
        f.write(overlay)
    
    print(f"Applied ManusLocal configuration to {openfang_config}")
    print("Restart OpenFang daemon: openfang start --config ~/.openfang/config.toml")

if __name__ == "__main__":
    main()
