#!/usr/bin/env bash
# =============================================================================
# ManusLocal — Complete Setup Script
# Run this once to set up everything on Justin's WSL machine.
# Usage: bash /home/justinleopard/projects/JustAi/LocalManus/scripts/setup_manuslocal.sh
# =============================================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LOG="$PROJECT_DIR/logs/setup.log"

mkdir -p "$PROJECT_DIR/logs" "$PROJECT_DIR/.dev-notepads" ~/Notes

echo "============================================================"
echo "ManusLocal Setup — $(date)"
echo "============================================================"
echo ""

# ── Step 1: Clone or update the repo ─────────────────────────────────────────
echo "[1/8] Verifying project directory..."
if [[ -d "$PROJECT_DIR/.git" ]]; then
    echo "  Already cloned. Pulling latest..."
    cd "$PROJECT_DIR" && git pull origin main 2>&1 | tail -3
else
    echo "  Cloning from GitHub..."
    cd ~/projects && git clone git@github.com:JustinJLeopard/LocalManus.git 2>&1
fi
echo "  ✓ Project directory ready at $PROJECT_DIR"

# ── Step 2: Create .env from known values ────────────────────────────────────
echo ""
echo "[2/8] Setting up .env file..."
if [[ ! -f "$PROJECT_DIR/.env" ]]; then
    cat > "$PROJECT_DIR/.env" << 'ENVEOF'
# ManusLocal Environment — Generated by setup script
# Fill in MANUS_API_URL, MANUS_API_KEY, MANUS_HAND_RELAY, MANUS_HAND_TOKEN when available

# Ollama (Windows host — auto-detected at startup by start_litellm.sh)
OLLAMA_MODEL=qwen3:30b-a3b-q4_K_M

# LiteLLM Proxy
LITELLM_KEY=sk-litellm-0544ee829e8c1f18c844742531845611
OPENAI_API_KEY=sk-litellm-0544ee829e8c1f18c844742531845611
OPENAI_BASE_URL=http://localhost:4000/v1

# Honcho Memory
HONCHO_API_KEY=hch-v3-a6kvt1aihusyc2p9f1qy01fs4ettcgn0eqfcdw4fjvwqpl9ko11xv7uccxpkugvr

# OpenRouter (from mini-swe-agent config)
OPENROUTER_API_KEY=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

# Telegram
TELEGRAM_BOT_TOKEN=8763657602:AAHxf8irACToLQrNFIH0q64FI0-7tT8leJE
TELEGRAM_CHAT_ID=

# Cloud Manus Delegation (fill in when available)
MANUS_API_URL=
MANUS_API_KEY=

# LocalManus Agent Routing
MANUSLOCAL_AGENT=assistant

# Manus Hand Relay (fill in)
MANUS_HAND_RELAY=
MANUS_HAND_TOKEN=
ENVEOF
    echo "  ✓ .env created"
else
    echo "  .env already exists, skipping"
fi

# ── Step 3: Install mini-swe-agent ───────────────────────────────────────────
echo ""
echo "[3/8] Installing mini-swe-agent..."
if [[ -d ~/mini-swe-agent ]]; then
    pip install -e ~/mini-swe-agent -q 2>&1 | tail -2
    echo "  ✓ mini-swe-agent installed"
else
    echo "  WARNING: ~/mini-swe-agent not found. Skipping."
fi

# ── Step 4: Install additional Python packages ───────────────────────────────
echo ""
echo "[4/8] Installing additional Python packages..."
sudo pip3 install -r "$PROJECT_DIR/requirements.txt" -q 2>&1 | tail -3
echo "  ✓ Packages installed"

# ── Step 5: Install the 'ml' CLI command ─────────────────────────────────────
echo ""
echo "[5/8] Installing 'ml' CLI command..."
mkdir -p ~/.local/bin
cat > ~/.local/bin/ml << 'MLEOF'
#!/usr/bin/env bash
# ManusLocal CLI entry point
PROJECT_DIR="${JUSTAI_LOCALMANUS_ROOT:-/home/justinleopard/projects/JustAi/LocalManus}"
[[ -f "$PROJECT_DIR/.env" ]] && { set -a; source "$PROJECT_DIR/.env"; set +a; }
python3 "$PROJECT_DIR/tools/ml_cli.py" "$@"
MLEOF
chmod +x ~/.local/bin/ml
# Ensure ~/.local/bin is in PATH
if ! grep -q 'local/bin' ~/.bashrc; then
    echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc
fi
echo "  ✓ 'ml' command installed at ~/.local/bin/ml"

# ── Step 6: Make all scripts executable ──────────────────────────────────────
echo ""
echo "[6/8] Setting script permissions..."
chmod +x "$SCRIPT_DIR"/*.sh 2>/dev/null || true
chmod +x "$SCRIPT_DIR"/*.py 2>/dev/null || true
echo "  ✓ Permissions set"

# ── Step 7: Apply OpenFang config overlay ────────────────────────────────────
echo ""
echo "[7/8] Applying OpenFang configuration..."
if command -v openfang &>/dev/null; then
    python3 "$SCRIPT_DIR/apply_openfang_config.py" 2>&1
    echo "  ✓ OpenFang config updated"
else
    echo "  WARNING: openfang command not found. Skipping config update."
fi

# ── Step 8: Initialize Honcho memory ─────────────────────────────────────────
echo ""
echo "[8/8] Verifying Honcho memory connection..."
source "$PROJECT_DIR/.env" 2>/dev/null || true
python3 "$PROJECT_DIR/memory/honcho_setup.py" --check 2>&1
echo "  ✓ Honcho verified"

echo ""
echo "============================================================"
echo "ManusLocal Setup Complete!"
echo "============================================================"
echo ""
echo "NEXT STEPS:"
echo ""
echo "1. Fix Ollama WSL access (run ONCE, then restart Ollama on Windows):"
echo "   bash $SCRIPT_DIR/fix_ollama_wsl.sh"
echo ""
echo "2. Start ManusLocal:"
echo "   bash $SCRIPT_DIR/start_manuslocal.sh"
echo ""
echo "3. Test the CLI:"
echo "   source ~/.bashrc && ml status"
echo ""
echo "4. Run your first task:"
echo "   ml task 'check system health and report'   # Uses the OpenFang assistant path"
echo ""
echo "Logs: $PROJECT_DIR/logs/"
echo "Docs: $PROJECT_DIR/README.md"
echo ""
echo "ManusLocal is ready. Persistent. Free. Forever."
